# Words for testing phonological derivation.
# Format: IPA = "gloss"

"ˈŋajʔ" = "I"
"ˈnjaʔ" = "you"
"ˈmja" = "not"
"ˈnjijs" = "two"
"ˈsum" = "three"
"ˈŋaʔ" = "five"
"ˈnjit" = "sun"
"ˈmjeŋ" = "name"
"ˈnjəʔ" = "ear"
"ˈŋja" = "fish"
"ˈkʰaʔ" = "bitter"
"ˈsrjat" = "kill"
"ˈduk" = "poison"
