//! The induced `rules.toml`, the `induction.md` trace, and the scoreboard report.

use super::boost::InducedInterval;
use super::objective::CascadeScore;
use super::refine::RefineTrace;
use crate::models::*;
use crate::py::{fixed, percent};

fn toml_string(value: &str) -> String {
    let escaped = value.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n").replace('\t', "\\t");
    format!("\"{escaped}\"")
}

pub fn render_induced_rules(inv: &RuleInventory) -> String {
    let mut lines: Vec<String> = vec![
        "# Induced sound-change cascade — generated by the rule inducer.".into(),
        "# Loadable as a normal rules.toml; times are real (composed from the interval spans).".into(),
        String::new(),
    ];
    for rule in inv.in_order() {
        lines.push(format!("[{}]", rule.id));
        if let Some(t) = rule.time {
            lines.push(format!("time = {t}"));
        }
        if let Some(name) = &rule.name {
            lines.push(format!("name = {}", toml_string(name)));
        }
        lines.push(format!("definition = {}", toml_string(&rule.raw_definition)));
        if let Some(d) = &rule.description {
            lines.push(format!("description = {}", toml_string(d)));
        }
        lines.push(String::new());
    }
    format!("{}\n", lines.join("\n").trim_end())
}

fn placement_label(placement: usize, rules_before: usize) -> String {
    if placement >= rules_before { "append".into() } else { format!("@{placement}") }
}

fn interval_section(interval: &InducedInterval) -> Vec<String> {
    let pct = if interval.assessed > 0 { interval.final_exact as f64 / interval.assessed as f64 } else { 0.0 };
    let mut lines = vec![
        format!("## Interval `{}`", interval.label),
        String::new(),
        format!(
            "**{} → {} / {} exact** ({}), fit **{} → {}** bits, **{} rules** induced — stopped: _{}_.",
            interval.start_exact,
            interval.final_exact,
            interval.assessed,
            percent(pct, 0),
            fixed(interval.start_fit, 0),
            fixed(interval.final_fit, 0),
            interval.rules.len(),
            interval.stopped
        ),
        String::new(),
    ];
    if interval.steps.is_empty() {
        lines.push("No rule lowered the loss — nothing induced.".into());
        lines.push(String::new());
        return lines;
    }
    lines.push("| # | rule | ΔL | Δfit | cost | words | exact | place |".into());
    lines.push("| ---: | --- | ---: | ---: | ---: | ---: | ---: | --- |".into());
    for (i, step) in interval.steps.iter().enumerate() {
        let number = i + 1;
        lines.push(format!(
            "| {number} | `{}` | {} | {} | {} | {} | {}→{} | {} |",
            step.definition,
            fixed(step.delta_l, 0),
            fixed(step.delta_fit, 0),
            fixed(step.rule_cost, 0),
            step.moved,
            step.exact_before,
            step.exact_after,
            placement_label(step.placement, number - 1)
        ));
    }
    lines.push(String::new());
    if !interval.shrink_log.is_empty() {
        lines.push(format!("**Shrink pass** removed {} now-redundant rule(s):", interval.shrink_log.len()));
        lines.push(String::new());
        lines.extend(interval.shrink_log.iter().map(|e| format!("- {e}")));
        lines.push(String::new());
    }
    lines
}

fn refine_section(trace: &RefineTrace) -> Vec<String> {
    let (s, f) = (&trace.start_score, &trace.final_score);
    let mut lines = vec![
        "## Phase B — global refinement".into(),
        String::new(),
        format!(
            "Composed cascade run from the true inputs over the whole lexicon: L **{} → {}**, final exact **{} → {} / {}**.",
            fixed(s.total(), 0),
            fixed(f.total(), 0),
            s.exact,
            f.exact,
            f.assessed
        ),
        String::new(),
    ];
    if !trace.removed.is_empty() {
        lines.push(format!("**Global shrink** retired {} rule(s):", trace.removed.len()));
        lines.push(String::new());
        lines.extend(trace.removed.iter().map(|e| format!("- {e}")));
        lines.push(String::new());
    }
    if !trace.added.is_empty() {
        lines.push(format!("**Final-residual boosting** appended {} rule(s):", trace.added.len()));
        lines.push(String::new());
        lines.extend(trace.added.iter().map(|d| format!("- `{d}`")));
        lines.push(String::new());
    }
    if trace.removed.is_empty() && trace.added.is_empty() {
        lines.push("Nothing changed — the composed cascade was already at a fixpoint.".into());
        lines.push(String::new());
    }
    lines
}

pub fn render_induction(intervals: &[InducedInterval], where_: &str, trace: Option<&RefineTrace>) -> String {
    let mut lines: Vec<String> = vec![
        format!("# Induction — {where_}"),
        String::new(),
        "Each interval's rule cascade, induced by greedy MDL boosting from the attested source".into(),
        "forms toward the attested targets. A rule is accepted only when it strictly lowers the".into(),
        "description length `L = fit_bits + rule_bits` — the bits it saves in the residual must".into(),
        "exceed the bits it costs to write. `ΔL` is that change (negative = a net saving), split".into(),
        "into its fit and rule-cost parts. `place` is where the rule was inserted in the".into(),
        "cascade (`append`, or `@i` when the placement search found an earlier slot fed a later".into(),
        "rule).".into(),
        String::new(),
    ];
    for interval in intervals {
        lines.extend(interval_section(interval));
    }
    if let Some(trace) = trace {
        lines.extend(refine_section(trace));
    }
    format!("{}\n", lines.join("\n").trim_end())
}

pub fn induction_summary_line(intervals: &[InducedInterval]) -> String {
    let rules: usize = intervals.iter().map(|i| i.rules.len()).sum();
    let exact: usize = intervals.iter().map(|i| i.final_exact).sum();
    let start: usize = intervals.iter().map(|i| i.start_exact).sum();
    let assessed: usize = intervals.iter().map(|i| i.assessed).sum();
    format!(
        "induced {rules} rule(s) across {} interval(s); exact {start} → {exact} / {assessed} — see induction.md",
        intervals.len()
    )
}

// ---- Scoreboard -------------------------------------------------------------------------------

/// `f"{x:{width},.0f}"`: rounded, with comma thousands separators, right-aligned.
fn grouped(x: f64, width: usize) -> String {
    let s = fixed(x, 0);
    let (sign, digits) = s.strip_prefix('-').map_or(("", s.as_str()), |d| ("-", d));
    let mut out = String::new();
    for (i, c) in digits.chars().enumerate() {
        if i > 0 && (digits.len() - i) % 3 == 0 {
            out.push(',');
        }
        out.push(c);
    }
    format!("{:>width$}", format!("{sign}{out}"))
}

/// `f"{x:.3g}"`.
pub fn general3(x: f64) -> String {
    if x == 0.0 {
        return if x.is_sign_negative() { "-0".into() } else { "0".into() };
    }
    let exp = format!("{:.2e}", x);
    let (mantissa, e) = exp.split_once('e').unwrap();
    let e: i32 = e.parse().unwrap();
    if !(-4..3).contains(&e) {
        let mantissa = mantissa.trim_end_matches('0').trim_end_matches('.');
        return format!("{mantissa}e{}{:02}", if e < 0 { '-' } else { '+' }, e.abs());
    }
    let s = fixed(x, (2 - e) as usize);
    if s.contains('.') { s.trim_end_matches('0').trim_end_matches('.').to_string() } else { s }
}

fn row(label: &str, s: &CascadeScore) -> String {
    format!(
        "| {label:<20} | {} | {} | {} | {:>4}/{:<4} | {:>6} |",
        grouped(s.fit_bits, 12),
        grouped(s.rule_bits, 10),
        grouped(s.total(), 12),
        s.exact,
        s.assessed,
        fixed(s.mean_distance, 3)
    )
}

pub struct Scoreboard {
    pub real_identity: CascadeScore,
    pub real_hand: CascadeScore,
    pub synthetic_identity: CascadeScore,
    pub synthetic_hand: CascadeScore,
}

pub fn render_scoreboard(b: &Scoreboard, where_: &str) -> String {
    let gap = b.real_identity.total() - b.real_hand.total();
    let lines = [
        format!("# Induction scoreboard — {where_}"),
        String::new(),
        "The MDL loss `L = fit_bits + rule_bits` of the identity cascade (no rules) and the".into(),
        "hand cascade, on the real lexicon and on the synthetic one (the hand cascade's own".into(),
        "output — the learnability floor, where its residual is zero). Every later induction".into(),
        "milestone is assessed against these numbers.".into(),
        String::new(),
        "| cascade | fit_bits | rule_bits | L (total) | exact | mean dist |".into(),
        "| --- | ---: | ---: | ---: | ---: | ---: |".into(),
        row("real · identity", &b.real_identity),
        row("real · hand", &b.real_hand),
        row("synthetic · identity", &b.synthetic_identity),
        row("synthetic · hand", &b.synthetic_hand),
        String::new(),
        format!("**Loss the hand rules buy on real data:** L(identity) − L(hand) = {} bits.", grouped(gap, 0)),
        String::new(),
        format!(
            "**Learnability floor:** the hand cascade's synthetic `fit_bits` is {} (target 0).",
            general3(b.synthetic_hand.fit_bits)
        ),
        String::new(),
    ];
    format!("{}\n", lines.join("\n").trim_end())
}

pub fn scoreboard_summary_line(b: &Scoreboard) -> String {
    let gap = b.real_identity.total() - b.real_hand.total();
    format!(
        "real: L(identity)={} → L(hand)={} (rules buy {} bits); synthetic hand fit={}",
        grouped(b.real_identity.total(), 0),
        grouped(b.real_hand.total(), 0),
        grouped(gap, 0),
        general3(b.synthetic_hand.fit_bits)
    )
}
